### ISSUE TITLE
Override keybindings

### ISSUE THREAD

**Issue by avucic** [EthanJWright/vs-tasks.nvim#1]
Hi, thanks for the plugin. Can you show how to override the default keymap? Thanks in advance

**Comment by EthanJWright** [comment]
Hi sorry just saw this - do you mean in regards to ctrl-v being used to split, enter being used to open, etc?

I don't have a config for that but can add one

**Comment by qozymandias** [comment]
This would also help me! if I could replace Ctrl-v and Ctrl-p with different keybindings that would be awesome!

**Comment by avucic** [comment]
@EthanJWright  Yes. Simple config to configure keymap. I forked your project and added launch.json parser to configure nvim dap as well as support Toggleterm. 
https://github.com/avucic/vs-tasks.nvim/commits/main
I'm new to lua/nvim and I guess I need to polish these features. Let me know if you have a plan to develop further this plugin. I'd rather follow your work

**Comment by EthanJWright** [comment]
Hey folks,

I added a configuration mapping for the telescope bindings. Docs are in the README!

@avucic I'll prob take a look at your PR to check out how you worked in DAP and toggleterm as I use both in my dev workflow, but haven't considered how I would want it integrated to this. 

Closing this issue as the initial problem should now be addressed!
