### ISSUE TITLE
Auto scrolling task panel

### ISSUE THREAD

**Issue by Willem-J-an** [EthanJWright/vs-tasks.nvim#14]
Hi @EthanJWright,
Do you think it would be possible to support handsoff auto scrolling along the task output? It is quite useful to keep an eye on the output while continuing to doing other stuff. Not sure how difficult this would be in neovim.

**Comment by EthanJWright** [comment]
So vs-tasks just uses your standard neovim terminal buffer - you can also swap it out using the command api that is provided to handle the command in a different manner with custom lua.

If I understand what you're saying, I get 'auto scrolling' by launching the task, exiting insert mode (look up the term key mappings or update them) and then if it isn't automatically scrolling, I'll hit G to make sure it is anchored to the bottom.

I could probably add a setting that does those things automatically if the setting is enabled, but until then hopefully that suffices! Feel free to open another PR if I misunderstood, or hit me up on discord GabenMessiah#0551
