### ISSUE TITLE
Error on execute tasks commands

### ISSUE THREAD

**Issue by leandrocunha** [EthanJWright/vs-tasks.nvim#18]
Hi, I'm a new in the vim world and I'm trying to use vs-tasks but when I try run the commands I got this error

![image](https://github.com/EthanJWright/vs-tasks.nvim/assets/1820920/9e766e14-8ffa-4352-b12b-3496d5f631d7)

How can I fix it?

**Comment by EthanJWright** [comment]
still getting this issue? sorry wasn't monitoring this well

**Comment by EthanJWright** [comment]
Closing as it's working for me and I need more info
