### ISSUE TITLE
Run several tasks in separate terminal

### ISSUE THREAD

**Issue by SteveWolligandt** [EthanJWright/vs-tasks.nvim#19]
Consider the case where I want to start a server and a client. I want to execute both at the same time. This seems currently not possible. When I start a second task it gets queued and executed after the first task finished. It would be nice if there is the possibility to run those two tasks in parallel.

**Comment by EthanJWright** [comment]
Is this true?  I put together this task:

```
{
      "label": "hello wait done",
      "command": "echo 'hello'; sleep 10; echo 'done'",
      "type": "shell"
    }
```

And I can run that, open vs tasks again, and run the command in a split, and they both run at the same time

**Comment by vansoest** [comment]
It would be nice if there is a multi terminal support e.g., like opening 3 terminals like in vs code via vsplit panes to have running the server and client and other stuff.

**Comment by EthanJWright** [comment]
Again it really seems like it supports that, what is the behavior you are getting? Can you give me an example task file and how you're using it?

**Comment by EthanJWright** [comment]
Closing as I believe this is supported
