### ISSUE TITLE
`vim.fn.json_decode` seems to have been deprecated.

### ISSUE THREAD

**Issue by Vssblt** [EthanJWright/vs-tasks.nvim#24]
Hello, I'm using newest version of neovim and it seems 'vim.fn.json_decode' is no longer supported, possibly because this function has been deprecated. The following error occurs:
```
attempt to call a string value
E5108: Error executing lua ...local/share/nvim/lazy/vs-tasks.nvim/lua/vstask/Parse.lua:191: attempt to index local 'tasks' (a nil value)
stack traceback:
        ...local/share/nvim/lazy/vs-tasks.nvim/lua/vstask/Parse.lua:191: in function 'Tasks'
        ...l/share/nvim/lazy/vs-tasks.nvim/lua/vstask/Telescope.lua:236: in function 'tasks'
        [string ":lua"]:1: in main chunk
```
I'm using the default configuration from the README.md.

To resolve this issue, replacing vim.fn.json_decode with vim.json.decode works. The changes are detailed in the following diff excerpt: 

``` diff
diff --git a/README.md b/README.md
index 46b66e3..e440d75 100644
--- a/README.md
+++ b/README.md
@@ -114,7 +114,7 @@ require("vstask").setup({
       direction = 'tab',
     }
   },
-  json_parser = 'vim.fn.json_decode'
+  json_parser = vim.json.decode
 })
 EOF
 ```
This modification works in my environment, I am sharing it to let you know. I'm wondering if the README.md file of your project intends to support the latest version of neovim and make modifications?

Here is my neovim version:
``` shell
nvim --version
NVIM v0.9.5
Build type: Debug
LuaJIT 2.1.1692716794
```

**Comment by EthanJWright** [comment]
great catch, thanks so much - updated the readme now.

feel free to open PRs in the future! but this was very helpful too
