### ISSUE TITLE
tasks.json not found

### ISSUE THREAD

**Issue by jamesonBradfield** [EthanJWright/vs-tasks.nvim#25]
hey yall, I have a godot project I am trying to setup C# debugging in and I have followed the Readme attached is my config for vstasks, and my tasks.json as well as the root(cwd) when trying to run vstask.launch
.vscode in cwd
![image](https://github.com/EthanJWright/vs-tasks.nvim/assets/113628216/db99ee5c-ee31-4250-909e-1ecf3ec3a747)
.vscode contents
![image](https://github.com/EthanJWright/vs-tasks.nvim/assets/113628216/52022b4f-4de0-4de6-9128-faff6a7277de)
VStask Config
![image](https://github.com/EthanJWright/vs-tasks.nvim/assets/113628216/1c1098b5-d31b-4f21-8dd9-537c39d24fe7)
https://pastebin.com/xMutTWV0

I have some questions related to this error, does vstask search in current buffer dir for .vscode/tasks.json?
or does it search in cwd?

Screenshot of error
![image](https://github.com/EthanJWright/vs-tasks.nvim/assets/113628216/cdb5b457-b772-4937-8141-6ab98890b85f)

tasks.json contents
![image](https://github.com/EthanJWright/vs-tasks.nvim/assets/113628216/6a189b14-a988-4dfb-ad17-1ce864210fb7)
https://pastebin.com/dSuZAX2x

**Comment by EthanJWright** [comment]
should be CWD, so where you launch nvim from - my workflow is to launch nvim from my project root, and then the tasks file is in `.vscode/tasks.json`

**Comment by EthanJWright** [comment]
you can hit me up on discord if you're having trouble (username: gabenmessiah)

**Comment by EthanJWright** [comment]
Going to close this assuming you figured it out
